# 3. 도형 그리기

##  빈 스케치북 만들기

In [36]:
import cv2
import numpy as np

# 세로 480 x 가로 640, 3 채널 (RGB) 에 해당하는 스케치북 만들기
img = np.zeros((480, 640, 3), dtype=np.uint8) #가로, 세로, 채널 / 전체 공간을 검은색으로 채움
img[:] = (255, 255, 255) # 전체 공간을 흰색으로 채움 / B, G, R
print(img)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


# 일부 영역 색칠

In [38]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8) #가로, 세로, 채널 / 전체 공간을 검은색으로 채움
img[100:200, 200:300] = (255, 255, 255)# 세로, 가로

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 직선
직선의 종류

1. cv2.LINE_4 : 상하좌우 4방향으로 연결된 선
1. cv2.LINE_8 : 대각선을 포함한 8 방향으로 연결된 선(기본값)
1. cv2.LINE_AA : 부드러운 선

In [39]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 255, 255) # BGR : Yellow, 색깔
THICKNESS = 3 # 선 두께

# 그릴 위치, 시작 점, 끝 점, 색깔, 두께, 선 종류
cv2.line(img, (50, 100), (400, 50), COLOR, THICKNESS, cv2.LINE_8)
cv2.line(img, (50, 200), (400, 150), COLOR, THICKNESS, cv2.LINE_4)
cv2.line(img, (50, 300), (400, 250), COLOR, THICKNESS, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 원

In [40]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (255, 255, 0) # BGR : 옥색
RADIUS = 50 # 반지름
THICKNESS = 10 # 선 두께

# 그릴 위치, 원의 중심점, 색깔, 선 두께, 선 종류
cv2.circle(img, (200, 100), RADIUS, COLOR, THICKNESS, cv2.LINE_AA) # 원 그리기
cv2.circle(img, (400, 100), RADIUS, COLOR, cv2.FILLED, cv2.LINE_AA) # 원을 꽉 채운다.

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 사각형

In [41]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 255, 0) # BGR : 초록색
THICKNESS = 3 # 선 두께

# 그릴 위치, 왼쪽 위 좌표, 오른쪽 위 좌표, 색깔, 선 두께, 선 종류
cv2.rectangle(img, (100, 100), (200, 200), COLOR, THICKNESS, cv2.LINE_AA)
cv2.rectangle(img, (300, 100), (400, 300), COLOR, cv2.FILLED, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 다각형

In [42]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 0, 255) # BGR : 빨간색
THICKNESS = 3 # 선 두께

pts1 = np.array([[100, 100], [200, 100], [100, 200]]) # 포인터 선언
pts2 = np.array([[200, 100], [300, 100], [300, 200]])

# 그릴 위치, 그릴 좌표들, 닫힘여부, 색깔, 선 두께, 선 종류
# cv2.polylines(img, [pts1], True, COLOR, THICKNESS, cv2.LINE_AA) # False일 때는 열린 도형, True일 때는 닫힌 도형
# cv2.polylines(img, [pts2], True, COLOR, THICKNESS, cv2.LINE_AA) # False일 때는 열린 도형, True일 때는 닫힌 도형
cv2.polylines(img, [pts1, pts2], True, COLOR, THICKNESS, cv2.LINE_AA) #위의 두개를 쓴 것과 같다

# 그릴 위치, 그릴 좌표들, 색깔, 선 종류
pts3 = np.array([[[100, 300], [200, 300], [100, 400]], [[200, 300], [300, 300], [300, 400]]])
cv2.fillPoly(img, pts3, COLOR, cv2.LINE_AA) # 꽉 찬 다각형

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 사람 얼굴 그리기

In [50]:
import cv2
import numpy as np

img = np.zeros((800, 800, 3), dtype=np.uint8)

COLOR = (255, 255, 255) # BGR : 흰색
RADIUS_EYE = 50 # 눈 반지름
RADIUS_MOUSE = 80 # 입 반지름
RADIUS_FACE = 300 # 얼굴 반지름
THICKNESS = 10 # 선 두께

# 그릴 위치, 원의 중심점, 색깔, 선 두께, 선 종류
cv2.circle(img, (300, 250), RADIUS_EYE, COLOR, cv2.FILLED, cv2.LINE_AA) # 원 그리기
cv2.circle(img, (500, 250), RADIUS_EYE, COLOR, cv2.FILLED, cv2.LINE_AA) # 원을 꽉 채운다.
cv2.circle(img, (400, 500), RADIUS_MOUSE, COLOR, THICKNESS, cv2.LINE_AA) # 원을 꽉 채운다.
cv2.circle(img, (400, 400), RADIUS_FACE, COLOR, THICKNESS, cv2.LINE_AA) # 원을 꽉 채운다.

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 다각형 응용

In [57]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0, 0, 255) # BGR : 빨간색
THICKNESS = 3 # 선 두께

pts1 = np.array([[[100, 100], [200, 100], [100, 200]], [[200, 100], [300, 100], [300, 200]]])
pts2 = np.array([[[100, 300], [200, 300], [100, 200]], [[200, 300], [300, 300], [300, 200]]])

# 그릴 위치, 그릴 좌표들, 닫힘여부, 색깔, 선 두께, 선 종류
cv2.fillPoly(img, pts1, COLOR, cv2.LINE_AA)
# 그릴 위치, 그릴 좌표들, 색깔, 선 종류
cv2.fillPoly(img, pts2, COLOR, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()